---
title: "SignalDetectionTool: R Package for signal detection of surveillance data"
output: 
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{SignalDetectionTool}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE, 
  warning = FALSE,
  fig.dim = c(4, 3), 
  fig.align = "center"
)
```


## Running the App 

Source the package

```{r setup}
library(SignalDetectionTool)
```

and run the app

```{r, eval=FALSE}
run_app()
```

### Upload Data 

The surveillance data to analyze must have the following format. 

```{r, child='../data/input/description.md'}
```


## Advanced Use 

Reading the data in R.

```{r, results='hide'}
input_path <- "../data/input/input.csv"
data <- read.csv(input_path)
shape <- sf::st_read("../data/shp/NUTS_RG_03M_2021_3035.shp")

```

### Preprocessing the data

```{r}
data <- dplyr::mutate(data, date_onset = dplyr::if_else(is.na(date_onset), 
                                                        date_report, 
                                                        date_onset))
data$age_group <- factor(data$age_group)
data$sex <- factor(data$sex)
```

### Plotting the time series

```{r}
results <- get_signals(data)

plot_time_series(results, interactive = TRUE)
plot_time_series(results, number_of_weeks = 10)
```

### Plotting the age groups

```{r}
ggiraph::girafe(ggobj = plot_agegroup_by(data))
```

### Creating tables 

```{r}
results <- get_signals(data, stratification = c("county", "sex", "age_group"))
create_results_table(results, interactive = TRUE)
```


### Regional visualization

```{r, include=FALSE}
# weird fix since match.fun only looks back through 2 layers of parent 
# environments for the named function
guide_colourbar_interactive <- function(...) ggiraph::guide_colourbar_interactive(...)

```


```{r}
signals_county <- get_signals(data, stratification = c("county_id"))
plot_regional(data, 
              signals_county, 
              shape, 
              country_id = unique(data$country_id), 
              regional_level = "county", 
              interactive = TRUE)
```

```{r}
signals_community <- get_signals(data, stratification = c("community_id"))
plot_regional(data, 
              signals_community, 
              shape, 
              country_id = unique(data$country_id), 
              regional_level = "community", 
              interactive = TRUE)
```



