---
title: "`r params$title`"
date: "Report generated on `r Sys.Date()`"
lang: "en"


params: 
  disease: "Pertussis"
  country: "Austria"
  number_of_weeks: 6
  category: "age_group"
  signals_agg: NULL 
  signals_padded: NULL
  intervention_date: NULL
  title: "Signal Detection Report"
---

`r paste(params$disease, params$category, sep  = "-")`
===========================================================================

<!-- Filtering strata -->
```{r}
categ <- params$category

patho_f <- tolower(params$disease)  
patho_f <- gsub("[~(),./?&!#<>\\]", "", patho_f) #remove special characters
patho_f <- gsub("\\s", "-", patho_f) # replace space with score

strat_text <- dplyr::case_when(
  categ == "age_group" ~ "agegroup",
  TRUE ~ categ
)
```

```{r}
# stratum with signals
s_df <- params$signals_agg %>% 
  SignalDetectionTool:::create_factor_with_unknown()

df <- params$signals_padded %>%
  dplyr::filter(.data$category %in% categ) %>%
  SignalDetectionTool:::create_factor_with_unknown()

number_stratum <- dplyr::n_distinct(df$stratum)

if (number_stratum <= 10) {
  p_height <- ceiling(dplyr::n_distinct(df$stratum) / 2) * 2
} else {
  p_height <- 12
}

pages <- ceiling(number_stratum / 12)

txt <- NULL
```

```{r, include=FALSE}
# Init Step to make sure that the dependencies are loaded
htmltools::tagList(plotly::ggplotly(ggplot2::ggplot()))
```

```{r}
# height of card: 460
# height of tab row: 35
# allow 155 characters max per tabrow

characters_strata <- dplyr::distinct(df, .data[["stratum"]]) %>%
  dplyr::pull() %>% paste(collapse = "     ") # "   " simulates space between tabs

tabrows <- ceiling(nchar(characters_strata)/155)
```

`r paste0("Row {.tabset data-height=", 425+tabrows*35, "}")`
-------------------------------------------------------------------------------
<!-- Print plot for each stratum -->

```{r, results='asis'}
for(st in unique(df$stratum)){
  # add marker to stratum with signals
  if(s_df$any_alarms[s_df$stratum == st]){
    st_f <- paste0("<b>\U2605 ", st, "</b>")
  } else {
    st_f <- st
  }
  cat("###", st_f, "\n")
  
  plot_stratum <- plot_time_series(
    df %>% dplyr::filter(.data[["stratum"]] == st),
    number_of_weeks = 52,
    intervention_date = params$intervention_date,
    interactive = TRUE
    )

  print(htmltools::tagList(plot_stratum))

  
  cat("\n\n\n")
}
```

Row
-------------------------------------------------------------------------------
[Go back](`r paste0(patho_f, ".html")`)

