---
title: "`r params$title`"
date: "Report generated on `r Sys.Date()`"
lang: "en"


params: 
  data: NULL
  disease: "Pertussis"
  country: "Austria"
  number_of_time_units: 6
  time_unit: "weekly"
  method: "farrington"
  alpha_upper: 0.05
  strata: !r c("county_id", "community_id", "sex", "age_group") 
  selected_filter_vars: NULL
  signals_padded: NULL
  signals_agg: NULL
  intervention_date: NULL
  title: "Signal Detection Report"
  exclude_outbreak_cases_from_fitting: false

---
```{css, echo = FALSE}
.hidden{
display: none;
}
```

```{r, echo=FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = FALSE, 
                      fig.align = 'center',
                      fig.width = 13,
                      fig.height = 5,
                      message = FALSE, 
                      warning = FALSE)
```

```{r include=FALSE}
# loading libraries in landing page level
library(dplyr)
library(SignalDetectionTool)
library(htmltools)
library(flexdashboard)
library(bslib)
```

```{r}
# Make the branded bslib colors directly available
brand_colors <- bs_get_variables(
  bs_global_get() ,
  c(
    "bg",
    "primary",
    "success",
    "info",
    "warning",
    "danger"
  )
)

# Use time unit labels
time_unit_label <- dplyr::case_when(
  params$time_unit == "weekly" && params$number_of_time_units == 1 ~ "week",
  params$time_unit == "weekly" && params$number_of_time_units > 1 ~ "weeks",
  params$time_unit == "biweekly" && params$number_of_time_units == 1 ~ "biweekly period",
  params$time_unit == "biweekly" && params$number_of_time_units > 1  ~ "biweekly periods",
  params$time_unit == "monthly" && params$number_of_time_units == 1 ~ "month",
  params$time_unit == "monthly" && params$number_of_time_units > 1  ~ "months"
)
```
<!-- Landing page -->

Landing Page
================================================================================

sidebar {.sidebar}
--------------------------------------------------------------------------------

```{r}
# For calculating week of start and end
if (params$time_unit %in% c("weekly", "biweekly")){
  records <- params$signals_padded %>% 
  dplyr::filter(!is.na(alarms)) %>% 
  dplyr::count(year, week) %>% 
  dplyr::mutate(yeartimeunit = sprintf("%d-W%02d", year, week))
} else if (params$time_unit == "monthly"){
  records <- params$signals_padded %>% 
  dplyr::filter(!is.na(alarms)) %>% 
  dplyr::count(year, month) %>% 
  dplyr::mutate(yeartimeunit = sprintf("%d-%02d", year, month))
  
}

# Selected pathogens
text_diseases <- ifelse(
  length(params$disease) == 1, 
  params$disease, 
  ifelse(length(params$disease) == 2, 
         paste0(params$disease, collapse = " and "),
         paste0(length(params$disease), " pathogens (see list to the right)")
         )

)

```

This report contains an overview of signals observed for the period `r head(records$yeartimeunit, 1)` to `r tail(records$yeartimeunit, 1)` for `r text_diseases` in `r params$country`. The signals were calculated using the `r params$method` algorithm`r ifelse(grepl("glm|farrington", params$method) && !is.null(params$alpha_upper), paste0(" with a p-value cutoff of ", params$alpha_upper, "."), paste0("."))` The following filters were applied in the application: `r paste0(ifelse(length(params$selected_filter_vars) != 0, paste(params$selected_filter_vars, collapse = ", "), "None"))`. `r ifelse(params$exclude_outbreak_cases_from_fitting == TRUE && grepl("glm", params$method), paste0(" Only cases not associated with outbreaks are used for training."), paste0(""))`

For each disease, an unstratified overview of the observed signals is provided, as well as stratified analyses by relevant characteristics.
The stratification may differ by disease.

```{r}
# compute unstratified number of cases in the last 6 time units
results_cases <- params$signals_agg %>% 
  dplyr::filter(is.na(category)) %>% 
  dplyr::select(pathogen,cases)
```

Row
--------------------------------------------------------------
### Summary
```{r}
# Summary all signals
tmp_df <- params$signals_agg %>%
  dplyr::mutate(
    category = dplyr::case_when(
      is.na(category)~"Unstratified", 
      .default = category
      )
  ) %>% 
  dplyr::group_by(pathogen, category) %>%
  dplyr::summarise(signals = sum(n_alarms))

# max number of signals in category in period
maxsignals <- params$signals_agg %>% 
  dplyr::group_by(category,pathogen) %>% 
  dplyr::summarise(max_signals = dplyr::n()*params$number_of_time_units) %>% 
  dplyr::mutate(
    category = dplyr::case_when(
      is.na(category)~"Unstratified", 
      .default = category
      )
  )
```

```{r}
# We colour the cell values according to the percentage of triggered signals
# We create two tables for this end

# table with signals, maxsignals, and percentages
s_tbl <- dplyr::left_join(tmp_df, maxsignals, by = c("pathogen", "category")) %>% dplyr::mutate(p_signals = signals/max_signals)

# format and join both tables
dt_abs <- s_tbl %>% 
  tidyr::pivot_wider(
    id_cols = pathogen,
    names_from = category,
    values_from = signals
  )

dt_perc <- s_tbl %>% 
  tidyr::pivot_wider(
    id_cols = pathogen,
    names_from = category,
    values_from = p_signals
  )

tmp_dt <- dplyr::left_join(dt_abs, dt_perc, by = "pathogen", suffix = c("", ".perc"))
```


```{r, out.width="1000px"}
# percentage column names
perc_cols <- names(tmp_dt)[stringr::str_ends(names(tmp_dt), ".perc")]
abs_cols <- stringr::str_remove(perc_cols, ".perc")

# create datatable with hidden percentage columns and replacing NA with - in absolute columns
dt <- DT::datatable(
  tmp_dt %>%
    dplyr::mutate(total = rowSums(dplyr::across(dplyr::where(is.integer)), na.rm = T)) %>%
    dplyr::right_join(results_cases, by = "pathogen") %>% 
    dplyr::relocate(cases, .after = "pathogen") %>%
    dplyr::mutate(
      pathogen_f = tolower(pathogen),
      pathogen_f = gsub("[~(),./?&!#<>\\]", "", pathogen_f),
      pathogen_f = gsub("\\s", "-", pathogen_f), 
      pathogen = paste0("<a href='report_pages/", pathogen_f,".html'>", pathogen,"</a>")) %>% 
    dplyr::select(-pathogen_f) %>% 
    dplyr::arrange(desc(total)) %>% 
    dplyr::mutate(dplyr::across(abs_cols, ~ tidyr::replace_na(as.character(.x) ,"-"))),
  rownames = FALSE,
  escape = FALSE,
  caption = paste0("Number of signals encountered in each stratification level in the last ",
                   params$number_of_time_units, " ", time_unit_label, "."),
  fillContainer = FALSE,
  class = list(stripe = FALSE),
  options = list(
    pageLength = 25,
    columnDefs = list(list(targets = perc_cols, visible = FALSE))
    )
  )

# colour each column according to corresponding percentage
cuts <- seq(0, 1, length.out = 11) # bins for colouring

# colours for interpolate, uses brand color
colours <- c(brand_colors["bg"], brand_colors["warning"], brand_colors["danger"])
values <- colorRamp(colours, bias = log(0.2)/log(0.5))(cuts)   # bias transforms warning value to 20%
values <- rgb(values[,1],
              values[,2],
              values[,3],
              maxColorValue = 255)
  
# assign each absolute column the colour formatting
for(cate in abs_cols){
  dt <- dt %>%
    DT::formatStyle(
      cate,
      valueColumns = paste0(cate, ".perc"),
      backgroundColor = DT::styleInterval(cuts[2:11], values)
    )
}

dt %>% DT::formatStyle("total", fontWeight = "bold")
```

<!-- Pathogen pages -->

```{r, results='asis', eval=FALSE}
path_sdt_report_body <- system.file("report","html_report", "SignalDetectionReport_body.rmd", package = "SignalDetectionTool")
src <- lapply(params$disease, function(i) {
  knitr::knit_expand(path_sdt_report_body, 
                     pathogen = i)
})

res <- knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = "\n")
```




