---
title: "`r params$title`"
date: "Report generated on `r Sys.Date()`"
lang: "en"


params:
  data: NULL
  disease: "Pertussis"
  country: "Austria"
  number_of_time_units: 6
  time_unit: "weekly"
  strata: !r c("county_id", "community_id", "sex", "age_group") 
  signals_padded: NULL
  signals_agg: NULL
  intervention_date: NULL
  title: "Signal Detection Report"
---

```{r}
# Make the branded bslib colors directly available
brand_colors <- bslib::bs_get_variables(
  bslib::bs_global_get() ,
  c(
    "bg",
    "primary",
    "success",
    "info",
    "warning",
    "danger"
  )
)
```


`r params$disease`
=====================================

<!-- Pathogen without stratification page -->

```{r}
# formatting pathogen name for links 
pate <- tolower(params$disease)  
pate <- gsub("[~(),./?&!#<>\\]", "", pate) #remove special characters
pate <- gsub("\\s", "-", pate) # replace space with score

s_agg <- params$signals_agg %>% 
  dplyr::filter(pathogen == params$disease)

s_pad <- params$signals_padded %>% 
  dplyr::filter(pathogen == params$disease)
```

```{r}
results_analysis <- s_pad %>%
  dplyr::filter(!is.na(alarms))

strata_per_category <- s_agg %>% 
  dplyr::count(.data$category)
  
```

Row
-------------------------------------------------------------------------------

### Number of cases
```{r}
time_unit_label <- dplyr::case_when(
  params$time_unit == "weekly" && params$number_of_time_units == 1 ~ "week",
  params$time_unit == "weekly" && params$number_of_time_units > 1 ~ "weeks",
  params$time_unit == "biweekly" && params$number_of_time_units == 1 ~ "biweekly period",
  params$time_unit == "biweekly" && params$number_of_time_units > 1  ~ "biweekly periods",
  params$time_unit == "monthly" && params$number_of_time_units == 1 ~ "month",
  params$time_unit == "monthly" && params$number_of_time_units > 1  ~ "months"
)

flexdashboard::valueBox(value = s_agg$cases[is.na(s_agg$category)], 
         caption = paste0("Number of ", params$disease," cases in the last ", params$number_of_time_units, " ", time_unit_label, "."),
         color = brand_colors["info"])
```

### Number of signals
```{r}
# signals across all strata
n_signals_time_unit <- sum(results_analysis$alarms)

# max possible signals in assessment period
possible_signals <- sum(dplyr::count(s_agg, category) %>% dplyr::pull(n)) * params$number_of_time_units

n_signals_time_unit_col <- ifelse(
  n_signals_time_unit < 0.10 * possible_signals, brand_colors["success"],
  ifelse(n_signals_time_unit < 0.50 * possible_signals, 
         brand_colors["warning"], brand_colors["danger"])
  )

flexdashboard::valueBox(value = n_signals_time_unit,
  caption = paste0("Number of signals for ", params$disease, " in the last ",
    params$number_of_time_units, " ", time_unit_label, "."),
  color = n_signals_time_unit_col
)
```

`r if(!is.null(params$strata)) "Row {data-height=200}"`
`r if(!is.null(params$strata)) "-------------------------------------------------------------------------------"`

```{r, results='asis', eval=!is.null(params$strata)}
for(cate in params$strata){

  cate_link <- paste0("[", cate, "](",pate ,"-", cate, ".html)")
  cat("### Signals in", cate_link, "\n\n")
  
  n.strata <- strata_per_category %>%
    dplyr::filter(category == cate) %>% 
    dplyr::pull(n)
  
  p <- s_pad %>% 
    dplyr::filter(category == cate) %>% 
    plot_signals_per_time_unit(n_strata = n.strata, interactive = TRUE, branding = brand_colors)
  
  print(htmltools::tagList(p))
  
  cat("\n\n")
}
```

`r if(!is.null(params$strata)) "Row {data-height=400}"`
`r if(!is.null(params$strata)) "-------------------------------------------------------------------------------"`

```{r, results='asis', eval=!is.null(params$strata)}
for(cate in params$strata){

  cate_link <- paste0("[", cate, "](",pate ,"-", cate, ".html)")
  cat("### Distribution by", cate_link, "\n\n")
  
  dist_plot <- SignalDetectionTool:::decider_barplot_map_table(
     s_agg,
     params$data,
     cate,
     interactive = TRUE, 
     page_length = 5
    ) 
  
  print(htmltools::tagList(dist_plot))
  
  cat("\n\n")
}
```

Row
-----------------------------------------------
### Unstratified timeseries 

```{r}
SignalDetectionTool::plot_time_series(
  s_pad %>%
    dplyr::filter(is.na(category)),
  intervention_date = params$intervention_date,
  interactive = TRUE
)
```

> `r paste("Number of", params$disease, "cases by time unit and signals,", params$country)`

Row {data-height=800}
-------------------------------------
### Signal Detection Table

```{r}
txt <- NULL

if (sum(results_analysis$alarms, na.rm = TRUE) != 0) {
  SignalDetectionTool::build_signals_table(
    s_pad,
    format = "DataTable", 
    page_length = 15
  )
} else {
  txt <- "No signals were detected."
}
```

```{r, results='asis'}
#|eval = is.character(txt)

cat(txt)
```

<!-- Strata timeseries pages -->

```{r, results='asis', eval=FALSE}
if(!is.null(params$strata)){
  path_sdt_report_strata <- system.file("report","html_report", "SignalDetectionReport_strata.rmd", package = "SignalDetectionTool")
  src <- lapply(params$strata, function(j) {
    knitr::knit_expand(path_sdt_report_strata, 
                       strat = j, pathogen = "{{pathogen}}")
  })
  
  res <- knitr::knit_child(text = unlist(src), quiet = TRUE)
  cat(res, sep = "\n")
}
```

Row
-------------------------------------------------------------------------------
[Go back](../SignalDetectionReport.html)
